<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
// gunakan model lokasi (dan barang jika perlu)
use App\Models\Lokasi;

class BarangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Ambil semua data lokasi dari tabel lokasis
        $lokasis = Lokasi::all();

        $barangs = [
            [
                'lokasi_id' => '1',
                'jurusan_id' => '1',
                'user_id' => '2',
                'nama' => 'PC 1',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana Umum',
                'nilai' => '1000000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Intel Core i5, RAM 8GB, SSD 256GB',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '1',
                'jurusan_id' => '1',
                'user_id' => '2',
                'nama' => 'PC 2',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana Umum',
                'nilai' => '1000000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Intel Core i5, RAM 8GB, SSD 256GB',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '1',
                'jurusan_id' => '1',
                'user_id' => '2',
                'nama' => 'PC 3',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana Umum',
                'nilai' => '1000000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Intel Core i5, RAM 8GB, SSD 256GB',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //-------------------------------

            [
                'lokasi_id' => '2',
                'jurusan_id' => '1',
                'user_id' => '2',
                'nama' => 'PC 4',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana Umum',
                'nilai' => '1000000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Intel Core i5, RAM 8GB, SSD 256GB',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '2',
                'jurusan_id' => '1',
                'user_id' => '2',
                'nama' => 'PC 5',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana Umum',
                'nilai' => '1000000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Intel Core i5, RAM 8GB, SSD 256GB',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '2',
                'jurusan_id' => '1',
                'user_id' => '2',
                'nama' => 'PC 6',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana Umum',
                'nilai' => '1000000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Intel Core i5, RAM 8GB, SSD 256GB',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //--------------------------------

            [
                'lokasi_id' => '3',
                'jurusan_id' => '1',
                'user_id' => '2',
                'nama' => 'PC 7',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana Umum',
                'nilai' => '1000000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Intel Core i5, RAM 8GB, SSD 256GB',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '3',
                'jurusan_id' => '1',
                'user_id' => '2',
                'nama' => 'PC 8',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana Umum',
                'nilai' => '1000000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Intel Core i5, RAM 8GB, SSD 256GB',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '3',
                'jurusan_id' => '1',
                'user_id' => '2',
                'nama' => 'Epson L3680',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana Umum',
                'nilai' => '1000000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Printer Scanner RGB',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /////////////////////////////////////

            [
                'lokasi_id' => '4',
                'jurusan_id' => '2',
                'user_id' => '2',
                'nama' => 'Mesin CNC 1',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana Umum',
                'nilai' => '10000000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'X Axis: 500mm  Y Axis: 380mm  Z Axis: 400mm  Table: 650x380mm  Max Loading: 200kg  Spindle Tapper: BT-30  Spindle Speed max: 12000rpm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '4',
                'jurusan_id' => '2',
                'user_id' => '2',
                'nama' => 'Mesin CNC 2',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana Umum',
                'nilai' => '10000000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'X Axis: 500mm  Y Axis: 380mm  Z Axis: 400mm  Table: 650x380mm  Max Loading: 200kg  Spindle Tapper: BT-30  Spindle Speed max: 12000rpm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '4',
                'jurusan_id' => '2',
                'user_id' => '2',
                'nama' => 'Mesin CNC 3',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana Umum',
                'nilai' => '10000000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'X Axis: 500mm  Y Axis: 380mm  Z Axis: 400mm  Table: 650x380mm  Max Loading: 200kg  Spindle Tapper: BT-30  Spindle Speed max: 12000rpm',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //-----------------------------------

            [
                'lokasi_id' => '5',
                'jurusan_id' => '2',
                'user_id' => '2',
                'nama' => 'Mesin CNC 4',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana Umum',
                'nilai' => '10000000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'X Axis: 500mm  Y Axis: 380mm  Z Axis: 400mm  Table: 650x380mm  Max Loading: 200kg  Spindle Tapper: BT-30  Spindle Speed max: 12000rpm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '5',
                'jurusan_id' => '2',
                'user_id' => '2',
                'nama' => 'Mesin CNC 5',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana Umum',
                'nilai' => '10000000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'X Axis: 500mm  Y Axis: 380mm  Z Axis: 400mm  Table: 650x380mm  Max Loading: 200kg  Spindle Tapper: BT-30  Spindle Speed max: 12000rpm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '5',
                'jurusan_id' => '2',
                'user_id' => '2',
                'nama' => 'Mesin CNC 6',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana Umum',
                'nilai' => '10000000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'X Axis: 500mm  Y Axis: 380mm  Z Axis: 400mm  Table: 650x380mm  Max Loading: 200kg  Spindle Tapper: BT-30  Spindle Speed max: 12000rpm',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //------------------------------------

            [
                'lokasi_id' => '6',
                'jurusan_id' => '2',
                'user_id' => '2',
                'nama' => 'Papan Tulis',
                'kategori' => 'Mebel',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '100000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Papan Tulis Putih 12 x 12 m',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '6',
                'jurusan_id' => '2',
                'user_id' => '2',
                'nama' => 'Meja',
                'kategori' => 'Mebel',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '100000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Meja Kayu 20 x 12 cm x 30 cm + laci',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '6',
                'jurusan_id' => '2',
                'user_id' => '2',
                'nama' => 'Kursi',
                'kategori' => 'Mebel',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '100000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Kursi Kayu 20 x 12 cm x 30 cm',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /////////////////////////////////////////////

            [
                'lokasi_id' => '7',
                'jurusan_id' => '3',
                'user_id' => '3',
                'nama' => 'Solder',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '10000000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Solder 200Watt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '7',
                'jurusan_id' => '3',
                'user_id' => '3',
                'nama' => 'Kabel',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '10000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Kabel 1m',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '7',
                'jurusan_id' => '3',
                'user_id' => '3',
                'nama' => 'Kabel',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '10000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Kabel 1m',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //---------------------------------

            [
                'lokasi_id' => '8',
                'jurusan_id' => '3',
                'user_id' => '3',
                'nama' => 'Papan Tulis',
                'kategori' => 'Mebel',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '100000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Papan Tulis Putih 12 x 12 m',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '8',
                'jurusan_id' => '3',
                'user_id' => '3',
                'nama' => 'Meja',
                'kategori' => 'Mebel',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '100000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Meja Kayu 20 x 12 cm x 30 cm + laci',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '8',
                'jurusan_id' => '3',
                'user_id' => '3',
                'nama' => 'Kursi',
                'kategori' => 'Mebel',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '100000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Kursi Kayu 20 x 12 cm x 30 cm',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //------------------------------------

            [
                'lokasi_id' => '9',
                'jurusan_id' => '3',
                'user_id' => '3',
                'nama' => 'Papan Tulis',
                'kategori' => 'Mebel',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '100000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Papan Tulis Putih 12 x 12 m',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '9',
                'jurusan_id' => '3',
                'user_id' => '3',
                'nama' => 'Meja',
                'kategori' => 'Mebel',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '100000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Meja Kayu 20 x 12 cm x 30 cm + laci',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '9',
                'jurusan_id' => '3',
                'user_id' => '3',
                'nama' => 'Kursi',
                'kategori' => 'Mebel',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '100000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Kursi Kayu 20 x 12 cm x 30 cm',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            ///////////////////////////////////////////

            [
                'lokasi_id' => '10',
                'jurusan_id' => '4',
                'user_id' => '4',
                'nama' => 'Kabel',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '10000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Kabel 1m',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '10',
                'jurusan_id' => '4',
                'user_id' => '4',
                'nama' => 'Sepeda Motor',
                'kategori' => 'Kendaraan',
                'sumber_dana' => 'Dana Sumbangan',
                'nilai' => '10000000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Sepeda Motor 100 cc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '10',
                'jurusan_id' => '4',
                'user_id' => '4',
                'nama' => 'Kabel',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '10000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Kabel 10m',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //------------------------------------------

            [
                'lokasi_id' => '11',
                'jurusan_id' => '4',
                'user_id' => '4',
                'nama' => 'Kabel',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '10000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Kabel 1m',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '11',
                'jurusan_id' => '4',
                'user_id' => '4',
                'nama' => 'Sepeda Motor',
                'kategori' => 'Kendaraan',
                'sumber_dana' => 'Dana Sumbangan',
                'nilai' => '10000000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Sepeda Motor 100 cc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '11',
                'jurusan_id' => '4',
                'user_id' => '4',
                'nama' => 'Kabel',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '10000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Kabel 10m',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //-----------------------------------

            [
                'lokasi_id' => '12',
                'jurusan_id' => '4',
                'user_id' => '4',
                'nama' => 'Mesin Kasir',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '120000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Mesin Kasir 1 unit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '12',
                'jurusan_id' => '4',
                'user_id' => '4',
                'nama' => 'Sepeda Motor',
                'kategori' => 'Kendaraan',
                'sumber_dana' => 'Dana Sumbangan',
                'nilai' => '10000000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Sepeda Motor 100 cc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '12',
                'jurusan_id' => '4',
                'user_id' => '4',
                'nama' => 'CCTV',
                'kategori' => 'Elektronik',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '10000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'CCTV 1 unit',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /////////////////////////////////////////

            [
                'lokasi_id' => '13',
                'jurusan_id' => '5',
                'user_id' => '5',
                'nama' => 'Kursi',
                'kategori' => 'Mebel',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '140000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Kursi Plastik',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '13',
                'jurusan_id' => '5',
                'user_id' => '5',
                'nama' => 'Kursi',
                'kategori' => 'Mebel',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '140000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Kursi Plastik',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '13',
                'jurusan_id' => '5',
                'user_id' => '5',
                'nama' => 'Kursi',
                'kategori' => 'Mebel',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '140000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Kursi Plastik',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //------------------------------------

            [
                'lokasi_id' => '14',
                'jurusan_id' => '5',
                'user_id' => '5',
                'nama' => 'Gitar',
                'kategori' => 'Alat Musik',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '140000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Gitar Akustik',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '14',
                'jurusan_id' => '5',
                'user_id' => '5',
                'nama' => 'Gitar',
                'kategori' => 'Alat Musik',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '140000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Gitar Listrik',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '14',
                'jurusan_id' => '5',
                'user_id' => '5',
                'nama' => 'Drum',
                'kategori' => 'Alat Musik',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '140000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Drum Elektrik',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //----------------------------------

            [
                'lokasi_id' => '15',
                'jurusan_id' => '5',
                'user_id' => '5',
                'nama' => 'Bola Basket',
                'kategori' => 'Alat Olahraga',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '140000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Bola Basket',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '15',
                'jurusan_id' => '5',
                'user_id' => '5',
                'nama' => 'Bola Basket',
                'kategori' => 'Alat Olahraga',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '140000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Bola Basket',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lokasi_id' => '15',
                'jurusan_id' => '5',
                'user_id' => '5',
                'nama' => 'Bola Volly',
                'kategori' => 'Alat Olahraga',
                'sumber_dana' => 'Dana BOS',
                'nilai' => '140000',
                'tanggal_beli' => '2023-01-01',
                'spesifikasi' => 'Bola Volly',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
        ];


        DB::table('barangs')->insert($barangs);
    }
}
